[project]
name = "rag-mastery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docx2txt>=0.9",
    "fastembed>=0.8.1",
    "ipywidgets>=8.1.9",
    "jupyter>=1.1.1",
    "langchain-huggingface>=1.2.2",
    "langchain-openai>=1.6.7",
    "langchain-text-splitters>=1.1.2",
    "matplotlib>=3.11.2",
    "python-dotenv>=1.2.3",
    "sentence-transformers>=6.1.0",
    "torch>=2.14.1",
    "transformers>=5.18.0",
]
